"""delete  phone_number column to users table

Revision ID: 90624e98024e
Revises: 9fec6fdee8ff
Create Date: 2024-11-04 12:02:40.975111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90624e98024e'
down_revision = '9fec6fdee8ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', mysql.VARCHAR(collation='utf8mb4_general_ci', length=15), nullable=True))

    # ### end Alembic commands ###
